blank_issues_enabled: false
contact_links:
  - name: Guía de actualización del proyecto
    url: https://github.com/AIDORA28/Polleria/blob/main/DOC/Guia-Actualizacion.md
    about: Antes de reportar, revisa los pasos para actualizar backend y frontend.